<a href="https://colab.research.google.com/github/saurabhsingh1411/MACHINE_LEARNING_PROJECTS/blob/main/Classification/IRIS_dataset_flower/IRIS_DATASET_CLASSIFIER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
iris=pd.read_csv('/content/iris_dataset.csv',header=None)

In [5]:
iris.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [7]:
print(iris.shape)

(150, 5)


In [10]:
X=iris.iloc[:,0:4]

In [12]:
y=iris.iloc[:,-1]

## Standarad Scaling and Preprocessing 

In [16]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

In [18]:
X=sc.fit_transform(X)

print(X.shape)

(150, 4)


In [19]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

y=le.fit_transform(y)

In [21]:
print(type(X))
print(type(y))
print(X.shape)
print(y.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(150, 4)
(150,)


#Model Building and Prediction

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(135, 4)
(15, 4)
(135,)
(15,)


1.Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
y_pred=rfc.predict(X_test)

In [28]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix as cm

print(classification_report(y_pred,y_test))

print('___________________________________________________________')

print(cm(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

___________________________________________________________
[[4 0 0]
 [0 7 0]
 [0 0 4]]


In [29]:
from sklearn import neighbors
classifier=neighbors.KNeighborsClassifier()

In [30]:
classifier.fit(X_train,y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [31]:
y_pred2=classifier.predict(X_test)

In [32]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix as cm

print(classification_report(y_pred2,y_test))

print('___________________________________________________________')

print(cm(y_pred2,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

___________________________________________________________
[[4 0 0]
 [0 7 0]
 [0 0 4]]
