<a href="https://colab.research.google.com/github/saurabhsingh1411/MACHINE_LEARNING_PROJECTS/blob/main/Classification/Diabetic%20Classifier/Diabetic_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [5]:
diabetic=pd.read_csv('pima-indians-diabetes.csv',header=None)

In [6]:
diabetic.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [7]:
print(diabetic.shape)

(768, 9)


In [11]:
X=diabetic.iloc[:,0:7].values
y=diabetic.iloc[:,-1].values

In [12]:
print(X.shape)
print(y.shape)

(768, 7)
(768,)


Model Building and Prepration 

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X=sc.fit_transform(X)

In [16]:
type(y)

numpy.ndarray

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

In [18]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(691, 7)
(77, 7)
(691,)
(77,)


In [19]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
y_pred1=lr.predict(x_test)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix as cm

print(classification_report(y_pred1,y_test))
print('____________________________________________________________________________')
print(cm(y_pred1,y_test))

              precision    recall  f1-score   support

           0       0.91      0.79      0.84        61
           1       0.46      0.69      0.55        16

    accuracy                           0.77        77
   macro avg       0.68      0.74      0.70        77
weighted avg       0.81      0.77      0.78        77

____________________________________________________________________________
[[48 13]
 [ 5 11]]


Model 2:randome forest classifier  

In [24]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [25]:
y_pred2=rfc.predict(x_test)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix as cm

print(classification_report(y_pred2,y_test))
print('____________________________________________________________________________')
print(cm(y_pred2,y_test))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82        54
           1       0.58      0.61      0.60        23

    accuracy                           0.75        77
   macro avg       0.71      0.71      0.71        77
weighted avg       0.76      0.75      0.75        77

____________________________________________________________________________
[[44 10]
 [ 9 14]]


MODEL 3

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [30]:
y_pred3=knn.predict(x_test)

In [31]:
from sklearn.metrics import classification_report,confusion_matrix as cm

print(classification_report(y_pred3,y_test))
print('____________________________________________________________________________')
print(cm(y_pred3,y_test))

              precision    recall  f1-score   support

           0       0.77      0.80      0.79        51
           1       0.58      0.54      0.56        26

    accuracy                           0.71        77
   macro avg       0.68      0.67      0.67        77
weighted avg       0.71      0.71      0.71        77

____________________________________________________________________________
[[41 10]
 [12 14]]
